### ISSUE TITLE
What namespace/assembly is AdoNetAppenderHelper in?

### ISSUE THREAD

**Issue by szalapski** [microknights/Log4NetHelper#1]
https://github.com/microknights/Log4NetHelper tells me 

"Now it is possible to set the connectionstring directly at runtime, instead of ConnectionStringName and/or ConnectinStringFile.  Simply call: `AdoNetAppenderHelper.SetConnectionString(configuration.GetConnectionString("log4net"));` Do this call immediately after log4net.Config.XmlConfigurator.Configure()"

I don't have a call to log4net.Config.XmlConfigurator.Configure(), as I am configuring in code with `            Hierarchy hierarchy = (Hierarchy)LogManager.GetRepository(System.Reflection.Assembly.GetEntryAssembly());`.  **Where should I call this helper?**

**Comment by szalapski** [comment]
Sorry, I didn't realize that this was a separate NuGet package: Log4NetHelper
 vs. Log4NetAdoAppender.  Got it now.

**Comment by microknights** [comment]
In general, the `SetConnectionString` must be call right after the configuration in done, either through runtime or loading the config file. At least before any registered loggers (`ILog`) is being called.
