### ISSUE TITLE
NET Core 3.1

### ISSUE THREAD

**Issue by Looooooka** [microknights/Log4NetHelper#2]
Any chance this could be updated to the latest net standard to work with net core 3.1?
It kinda broke at 3.0 and 3.1.

**Comment by microknights** [comment]
hhmm, didn't get any notifications on your post @Looooooka 🤔 So i am a bit late here.

The library supports .Net Standard v2.1 which should be equal to .Net Core v3.0 and v3.1. So can you be at bit more detailed on "kinda broke"?

I am just about to release this package and Log4NetAdoNetAppender, so it could be cool to have all issues fixed.

**Comment by Looooooka** [comment]
I believe you helped me get to the bottom of the issue in the apender project. Forgot I posted it here as well. Consider it closed :)
